"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from redis import StrictRedis

from cloud.cloud_services import Hetzner

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

redis = StrictRedis(host="localhost", port=6379, db=0, decode_responses=True)
hetzner = Hetzner()
PAGINATION_BLOGS = 24
PAGINATION_TRANSACTIONS = 24
PAGINATION_INVOICES = 24
PAGINATION_HISTORY_LOGIN = 24
PAGINATION_SERVERS = 24
PAGINATION_SITEMAP = 1000

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mt1qqvadao9xgqc+j@tl@ib=u@_ar%4mkdz455tg*@gc_-za$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['maxnovin.com', 'dashboard.maxnovin.com', 'cloud.maxnovin.com', 'api.maxnovin.com']

SCHEME = "https://"
DOMAIN_URL = SCHEME + ALLOWED_HOSTS[0] 
DASHBOARD_URL = SCHEME + ALLOWED_HOSTS[1] + "/"
CLOUD_URL = SCHEME + ALLOWED_HOSTS[2] + "/"
API_URL = SCHEME + ALLOWED_HOSTS[3] + "/"
LOGIN_URL = DASHBOARD_URL + "login/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'cloud.apps.CloudConfig',
    'account.apps.AccountConfig',
    'blog.apps.BlogConfig',
    'main.apps.MainConfig',
    'wallet.apps.WalletConfig',
    'api.apps.ApiConfig',

    'rest_framework',
    'widget_tweaks',
    'ckeditor',
    'ckeditor_uploader',
    "corsheaders",
]

MIDDLEWARE = [  
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

CSRF_COOKIE_DOMAIN = "." + ALLOWED_HOSTS[0]
CSRF_TRUSTED_ORIGINS = ["https://*.maxnovin.com"]
SESSION_COOKIE_DOMAIN = "." + ALLOWED_HOSTS[0]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_context',
                'dashboard.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'maxnovin',
        'USER': 'usermaxnovin',
        'PASSWORD': '!@maxnovin.com%^&2023',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.User'
swappable = 'AUTH_USER_MODEL'

# Zarinpal
SANDBOX = 'next'
MERCHANT = 'de68f8da-777a-4cfd-8bd9-76fc385edeaa'

#SMS
SMS_API_KEY = "6exdLsSFJJUMSzLgjzgzeJsbhQvir0UqQWw7H6OokQNNKxrX4OfdnibCmTrKvfT7"
SMS_PHONE = "30007732902984"
SMS_TEMPLATE_ID = 167187

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': '400px',
        'width': '100%',
        'tabSpaces': 4,
        "allowedContent": True,
        "removePlugins": "stylesheetparser",
        "fillEmptyBlocks": False
    },
}
