"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from redis import StrictRedis

from cloud.cloud_services import Hetzner, Linode

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

redis = StrictRedis(host="localhost", port=6379, db=0, decode_responses=True)
hetzner = Hetzner()
linode = Linode()
PAGINATION_BLOGS = 24
PAGINATION_TRANSACTIONS = 24
PAGINATION_HISTORY_LOGIN = 24
PAGINATION_INVOICES = 24
PAGINATION_SERVERS = 24
PAGINATION_SITEMAP = 1000

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mt1qqvadao9xgqc+j@tl@ib=u@_ar%4mkdz455tg*@gc_-za$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1"]

SCHEME = "http://"
DOMAIN_URL = SCHEME + ALLOWED_HOSTS[0]
PANEL_URL = DOMAIN_URL + ":8001/"
CLOUD_URL = DOMAIN_URL + ":8001/cloud/"
API_URL = DOMAIN_URL + ":8001/api/"
LOGIN_URL = PANEL_URL + "accounts/login/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'cloud.apps.CloudConfig',
    'account.apps.AccountConfig',
    'panel.apps.PanelConfig',
    'blog.apps.BlogConfig',
    'main.apps.MainConfig',
    'wallet.apps.WalletConfig',
    'api.apps.ApiConfig',
    'widget_tweaks',
    'rest_framework',

    'ckeditor',
    'ckeditor_uploader',

    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://127.0.0.1:8001"]
CSRF_COOKIE_DOMAIN = ALLOWED_HOSTS[0]
SESSION_COOKIE_DOMAIN = ALLOWED_HOSTS[0]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_context',
                'panel.context_processors.site_context'
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.User'
swappable = 'AUTH_USER_MODEL'

# Zarinpal
SANDBOX = 'next'
MERCHANT = '4f6ad457-68cd-43c6-884d-fc9cbf9a05ec'

#SMS
SMS_API_KEY = "UIHapo5M4LZthKwT0h1Xsk3xPvshMQR9oWq0xvDV9JLqYcLkN0aV0L2RqV4PYN88"
SMS_PHONE = "30007732902984"
SMS_TEMPLATE_ID = 746036

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': '400px',
        'width': '100%',
        'tabSpaces': 4,
        "allowedContent": True,
        "removePlugins": "stylesheetparser",
        "fillEmptyBlocks": False,
        'enterMode': 2
    },
}
